apiVersion: v1
kind: Service
metadata:
  namespace: 230052-adrian
  name: utxj-workshop-api
spec:
  selector:
    app: utxj-workshop-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
